// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_tech_task/test/presentation/posts_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i1;
import 'package:flutter_tech_task/app_navigator.dart' as _i3;
import 'package:flutter_tech_task/domain/entities/post_summary.dart' as _i7;
import 'package:flutter_tech_task/domain/entities/result.dart' as _i6;
import 'package:flutter_tech_task/domain/usecases/watch_post_summaries_use_case.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake
    implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppNavigator extends _i2.Mock implements _i3.AppNavigator {
  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_0<_i1.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i1.GlobalKey<_i1.NavigatorState>);

  @override
  set navigatorKey(_i1.GlobalKey<_i1.NavigatorState>? value) =>
      super.noSuchMethod(
        Invocation.setter(#navigatorKey, value),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<T?> pushNamed<T extends Object?>(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushNamed, [routeName], {#arguments: arguments}),
            returnValue: _i4.Future<T?>.value(),
            returnValueForMissingStub: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<void> pushScaffoldMessenger<T extends Object?>(
    _i3.ScaffoldMessengerRoute? route, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushScaffoldMessenger,
              [route],
              {#arguments: arguments},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [WatchPostSummariesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchPostSummariesUseCase extends _i2.Mock
    implements _i5.WatchPostSummariesUseCase {
  @override
  _i4.Stream<_i6.Result<List<_i7.PostSummary>>> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i4.Stream<_i6.Result<List<_i7.PostSummary>>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.Result<List<_i7.PostSummary>>>.empty(),
          )
          as _i4.Stream<_i6.Result<List<_i7.PostSummary>>>);

  @override
  _i4.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
